Select 	cast(so.serviceofferingid as bigint) SERVICE_OFFERING_KEY, 
so.availabilityCheckExcludeInd AVAIL_CHECK_EXCL_IND, 
so.comments COMMENTS_TEXT, 
so.deliveryFrequency DELIVERY_FREQ_CODE, 
'' DELIVERY_FREQ_EN_DESC, 
'' DELIVERY_FREQ_FR_DESC, 
so.deliveryType DELIVERY_TYPE_CODE, 
cti_dt.EN_DESC DELIVERY_TYPE_EN_DESC, 
cti_dt.FR_DESC DELIVERY_TYPE_FR_DESC, 
so.descriptionTextID DESCRIPTION_TEXT_ID, 
so.endDate END_DATE, 
so.MAXIMUMUNITS MAX_UNITS_QUANTITY, 
so.nameTextID NAME_TEXT_ID, 
so.placementPmtInd PLACEMENT_PMT_IND, 
so.provisionMethod PROVISION_METHOD_CODE, 
'' PROVISION_METHOD_EN_DESC, 
'' PROVISION_METHOD_FR_DESC, 
so.recordStatus RECORD_STATUS_CODE, 
cti_s.EN_DESC RECORD_STATUS_EN_DESC, 
cti_s.FR_DESC RECORD_STATUS_FR_DESC, 
so.reference REFERENCE_NAME, 
so.referenceUpper REFERENCE_UPPER_NAME, 
so.saPlmtInhibitInd SA_PLACEMENT_INHIBIT_IND, 
so.description SERVICE_DESC, 
so.name SERVICE_NAME, 
so.serviceOfferingID SERVICE_OFFERING_ID, 
so.nameUpper SERVICE_UPPER_NAME, 
so.singleOrMultipleClients SINGLE_MULT_CLIENTS_FLAG, 
so.specialConditionType SPECIAL_COND_TYPE_CODE, 
'' SPECIAL_COND_TYPE_EN_DESC, 
'' SPECIAL_COND_TYPE_FR_DESC, 
so.startDate START_DATE, 
so.trainingInd TRAINING_IND, 
so.unitFrequency UNIT_FREQ_PERIOD_CODE, 
'' UNIT_FREQ_PERIOD_EN_DESC, 
'' UNIT_FREQ_PERIOD_FR_DESC, 
so.unitOfMeasure UOM_CODE, 
cti_um.EN_DESC UOM_EN_DESC, 
cti_um.EN_DESC UOM_FR_DESC
--cast(so.__Start_At.op_ts as timestamp) Effective_Start_DT
From {bronze_database}.cpin_curam_serviceoffering so
left join {bronze_database}.cpin_curam_codetableitem_flat cti_dt on so.deliveryType = cti_dt.code and cti_dt.TABLENAME ='SODeliveryType' 
left join {bronze_database}.cpin_curam_codetableitem_flat cti_s on so.recordStatus = cti_s.code and cti_s.TABLENAME ='RecordStatus' 
left join {bronze_database}.cpin_curam_codetableitem_flat cti_um on so.UnitOfMeasure = cti_um.code and cti_um.TABLENAME ='UnitOfMeasure' 
