Select 
	ATTACHMENTLINKID AS ATTACHMENT_LINK_ID,
	CONCERNROLEID AS ATTACHMENT_LINK_CONCERNROLE_ID,
	ATTACHMENTID AS ATTACHMENT_ID,
	STATUSCODE AS STATUS_CODE,
	DESCRIPTION AS DESCRIPTION,
	DATERECEIVED AS DATE_RECEIVED
From {bronze_database}.cpin_curam_concernroleattachmentlink