Select 	
l.ARCHIVE_TEAM_ID ARCHIVE_TEAM_ID, 
l.DESCRIPTION DESCRIPTION, 
l.ID, 
l.IS_ACTIVE_FLAG IS_ACTIVE_FLAG, 
l.LOCATION_CODE LOCATION_CODE, 
l.LOCATION_CODE_NUM LOCATION_CODE_NUM, 
l.LOCATION_CODE_NUM2 LOCATION_CODE_NUM2, 
l.LOCATION_TYPE_ID LOCATION_TYPE_ID, 
l.PROGRAM_ID PROGRAM_ID
From {bronze_database}.cpin_cams_location l 