SELECT  cast(pe.PROVIDERENQUIRYID as bigint) ENQUIRY_KEY, 
pee.ABORIGINALANCESTRYCODE ABORIGINAL_ANCESTRY_LIST, 
pe.ADDITIONALINFORMATION ADDITIONAL_INFORMATION_TEXT, 
pe.ADDITIONALNAME ADDITIONAL_NAME, 
pe.ATTENDEDMEETING ATTENDED_MEETING_IND, 
pe.AVAILABILITYFORCONTACT AVAILABILITY_FOR_CONTACT_TEXT, 
pe.PROVIDERCATEGORYPERIODID CATEGORY_PERIOD_ID, 
pee.CLOSURECOMMENTS  CLOSURE_COMMENTS_TEXT, 
pee.CLOSUREREASON CLOSURE_REASON_CODE, 
coalesce(cti_cr.EN_DESC,'') CLOSURE_REASON_EN_DESC, 
coalesce(cti_cr.FR_DESC,'') CLOSURE_REASON_FR_DESC, 
pe.CONFIRMEDMEETINGDETAILS CONFIRMED_MEETING_DETAILS_IND, 
pee.PROVIDERCONSENTFORCAPTURE CONSENT_FOR_CAPTURE_IND, 
pee.PROVIDERCONSENTFORSEARCH CONSENT_FOR_SEARCH_IND, 
pee.EMAILADDRESSID EMAIL_ADDRESS_ID, 
pe.NAME ENQUIRIED_BY_NAME, 
pe.ENDDATE ENQUIRY_END_DATE, 
pe.PROVIDERENQUIRYID ENQUIRY_ID, 

pe.REFERENCENUMBER ENQUIRY_REFERENCE_NUMBER, 
pe.ENQUIRYDATE ENQUIRY_START_DATE, 
pe.HOMEADDRESSID HOME_ADDRESS_ID, 
pe.HOMEPHONENUMBERID HOME_PHONE_NUMBER_ID, 
pe.NOOFCHILDREN HOUSEHOLD_CHILDREN_COUNT, 
pee.INDIGENOUSGROUPCODE INDIGENOUS_GROUP_LIST, 
pee.INDIGENOUSPERSONIND INDIGENOUS_PERSON_IND, 
pe.MOBILEPHONENUMBERID MOBILE_PHONE_NUMBER_ID, 
pe.OBTAINEDAPPLICATIONFORM OBTAINED_APPL_FORM_IND, 
-- pe.ADDITIONALINFORMATION_OLD OLD_ADDITIONAL_INFORMATION_TEXT,   -- missing in pe table
'' OLD_ADDITIONAL_INFORMATION_TEXT,
pe.ORGOBJECTLINKID ORG_OBJECT_LINK_ID, 
pe.OWNERNAME OWNER_NAME, 
pe.PREFERREDCOMMUNICATION PREF_COMMUNICATION_CODE, 
coalesce(cti_pcc.EN_DESC,'') PREF_COMMUNICATION_EN_DESC, 
coalesce(cti_pcc.FR_DESC,'') PREF_COMMUNICATION_FR_DESC, 

pe.PREFERREDLANGUAGE PREF_LANGUAGE_CODE, 
coalesce(cti_pl.EN_DESC,'') PREF_LANGUAGE_EN_DESC, 
coalesce(cti_pl.FR_DESC,'') PREF_LANGUAGE_FR_DESC, 

pe.PREFERREDSESSION PREF_TRAINING_SESSION_DESC, 
pe.REASONFORENQUIRY REASON_FOR_ENQUIRY_CODE, 
coalesce(cti_re.EN_DESC,'') REASON_FOR_ENQUIRY_EN_DESC, 
coalesce(cti_re.FR_DESC,'') REASON_FOR_ENQUIRY_FR_DESC, 
pe.RECORDSTATUS RECORD_STATUS_CODE, 
coalesce(cti_s.EN_DESC,'') RECORD_STATUS_EN_DESC, 
coalesce(cti_s.FR_DESC,'') RECORD_STATUS_FR_DESC, 
pe.SCHEDULEDMEETING SCHEDULED_MEETING_DESC, 
pe.NAMEUPPER UPPER_NAME, 
pe.WORKADDRESSID WORK_ADDRESS_ID, 
pe.WORKPHONENUMBERID WORK_PHONE_NUMBER_ID
From {bronze_database}.cpin_curam_providerenquiry pe
left join {bronze_database}.cpin_curam_mcysproviderenquiryext pee on pe.PROVIDERENQUIRYID = pee.PROVIDERENQUIRYID 
left join {bronze_database}.cpin_curam_codetableitem_flat cti_cr on pee.CLOSUREREASON = cti_cr.code and cti_cr.TABLENAME ='MCYSInquiryClosureReasons' 
left join {bronze_database}.cpin_curam_codetableitem_flat cti_pcc on pe.PREFERREDCOMMUNICATION = cti_pcc.code and cti_pcc.TABLENAME ='CommunicationMethod' 
left join {bronze_database}.cpin_curam_codetableitem_flat cti_pl on pe.PREFERREDLANGUAGE = cti_pl.code and cti_pl.TABLENAME ='Language' 
left join {bronze_database}.cpin_curam_codetableitem_flat cti_re on pe.REASONFORENQUIRY = cti_re.code and cti_re.TABLENAME ='ReasonForEnquiry'
left join {bronze_database}.cpin_curam_codetableitem_flat cti_s on pe.RECORDSTATUS = cti_s.code and cti_s.TABLENAME ='EnquiryStatus' 
